"""initial_schema

Revision ID: ba5c2b63e16d
Revises: 
Create Date: 2026-09-03 00:29:24.526959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ba5c2b63e16d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'principal_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('cases', 'overdue_amount',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('cases', 'overdue_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('cases', 'payment_promise',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('cases_case_id_key'), 'cases', type_='unique')
    op.drop_index(op.f('idx_cases_assigned_to'), table_name='cases')
    op.drop_index(op.f('idx_cases_created_at'), table_name='cases')
    op.drop_index(op.f('idx_cases_customer_id'), table_name='cases')
    op.drop_index(op.f('idx_cases_overdue_days'), table_name='cases')
    op.drop_index(op.f('idx_cases_status'), table_name='cases')
    op.create_index(op.f('ix_cases_case_id'), 'cases', ['case_id'], unique=True)
    op.create_index(op.f('ix_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('ix_cases_customer_id'), 'cases', ['customer_id'], unique=False)
    op.create_index(op.f('ix_cases_overdue_days'), 'cases', ['overdue_days'], unique=False)
    op.create_index(op.f('ix_cases_status'), 'cases', ['status'], unique=False)
    op.drop_constraint(op.f('fk_assigned_to'), 'cases', type_='foreignkey')
    op.drop_index(op.f('idx_compliance_violations_case_id'), table_name='compliance_violations')
    op.drop_index(op.f('idx_compliance_violations_detected_at'), table_name='compliance_violations')
    op.drop_index(op.f('idx_compliance_violations_resolved'), table_name='compliance_violations')
    op.create_index(op.f('ix_compliance_violations_detected_at'), 'compliance_violations', ['detected_at'], unique=False)
    op.create_index(op.f('ix_compliance_violations_resolved'), 'compliance_violations', ['resolved'], unique=False)
    op.drop_constraint(op.f('fk_case_violation'), 'compliance_violations', type_='foreignkey')
    op.drop_constraint(op.f('fk_contact_violation'), 'compliance_violations', type_='foreignkey')
    op.create_foreign_key(None, 'compliance_violations', 'cases', ['case_id'], ['id'])
    op.create_foreign_key(None, 'compliance_violations', 'contact_history', ['contact_id'], ['id'])
    op.drop_constraint(op.f('contact_history_contact_id_key'), 'contact_history', type_='unique')
    op.drop_index(op.f('idx_contact_history_case_id'), table_name='contact_history')
    op.drop_index(op.f('idx_contact_history_contact_time'), table_name='contact_history')
    op.drop_index(op.f('idx_contact_history_created_by'), table_name='contact_history')
    op.create_index(op.f('ix_contact_history_contact_id'), 'contact_history', ['contact_id'], unique=True)
    op.create_index(op.f('ix_contact_history_contact_time'), 'contact_history', ['contact_time'], unique=False)
    op.drop_constraint(op.f('fk_case'), 'contact_history', type_='foreignkey')
    op.create_foreign_key(None, 'contact_history', 'cases', ['case_id'], ['id'])
    op.alter_column('customers', 'monthly_income',
               existing_type=sa.NUMERIC(precision=15, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('customers', 'registration_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_constraint(op.f('customers_customer_id_key'), 'customers', type_='unique')
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.alter_column('genai_audit', 'input_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('genai_audit', 'output_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_genai_audit_case_id'), table_name='genai_audit')
    op.drop_index(op.f('idx_genai_audit_created_at'), table_name='genai_audit')
    op.drop_index(op.f('idx_genai_audit_service_type'), table_name='genai_audit')
    op.create_index(op.f('ix_genai_audit_created_at'), 'genai_audit', ['created_at'], unique=False)
    op.create_index(op.f('ix_genai_audit_service_type'), 'genai_audit', ['service_type'], unique=False)
    op.drop_constraint(op.f('fk_case_audit'), 'genai_audit', type_='foreignkey')
    op.create_foreign_key(None, 'genai_audit', 'cases', ['case_id'], ['id'])
    op.drop_index(op.f('idx_rules_is_active'), table_name='rules')
    op.drop_index(op.f('idx_rules_rule_type'), table_name='rules')
    op.drop_constraint(op.f('rules_rule_id_key'), 'rules', type_='unique')
    op.create_index(op.f('ix_rules_is_active'), 'rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_rules_rule_id'), 'rules', ['rule_id'], unique=True)
    op.create_index(op.f('ix_rules_rule_type'), 'rules', ['rule_type'], unique=False)
    op.drop_constraint(op.f('script_templates_template_id_key'), 'script_templates', type_='unique')
    op.create_index(op.f('ix_script_templates_template_id'), 'script_templates', ['template_id'], unique=True)
    op.alter_column('task_queue', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('task_queue', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_task_queue_status'), table_name='task_queue')
    op.drop_index(op.f('idx_task_queue_task_type'), table_name='task_queue')
    op.drop_constraint(op.f('task_queue_task_id_key'), 'task_queue', type_='unique')
    op.create_index(op.f('ix_task_queue_status'), 'task_queue', ['status'], unique=False)
    op.create_index(op.f('ix_task_queue_task_id'), 'task_queue', ['task_id'], unique=True)
    op.create_index(op.f('ix_task_queue_task_type'), 'task_queue', ['task_type'], unique=False)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_task_queue_task_type'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_task_id'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_status'), table_name='task_queue')
    op.create_unique_constraint(op.f('task_queue_task_id_key'), 'task_queue', ['task_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_task_queue_task_type'), 'task_queue', ['task_type'], unique=False)
    op.create_index(op.f('idx_task_queue_status'), 'task_queue', ['status'], unique=False)
    op.alter_column('task_queue', 'result',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('task_queue', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_script_templates_template_id'), table_name='script_templates')
    op.create_unique_constraint(op.f('script_templates_template_id_key'), 'script_templates', ['template_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_rules_rule_type'), table_name='rules')
    op.drop_index(op.f('ix_rules_rule_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_is_active'), table_name='rules')
    op.create_unique_constraint(op.f('rules_rule_id_key'), 'rules', ['rule_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_rules_rule_type'), 'rules', ['rule_type'], unique=False)
    op.create_index(op.f('idx_rules_is_active'), 'rules', ['is_active'], unique=False)
    op.drop_constraint(None, 'genai_audit', type_='foreignkey')
    op.create_foreign_key(op.f('fk_case_audit'), 'genai_audit', 'cases', ['case_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_genai_audit_service_type'), table_name='genai_audit')
    op.drop_index(op.f('ix_genai_audit_created_at'), table_name='genai_audit')
    op.create_index(op.f('idx_genai_audit_service_type'), 'genai_audit', ['service_type'], unique=False)
    op.create_index(op.f('idx_genai_audit_created_at'), 'genai_audit', ['created_at'], unique=False)
    op.create_index(op.f('idx_genai_audit_case_id'), 'genai_audit', ['case_id'], unique=False)
    op.alter_column('genai_audit', 'output_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('genai_audit', 'input_data',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.create_unique_constraint(op.f('customers_customer_id_key'), 'customers', ['customer_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('customers', 'registration_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('customers', 'monthly_income',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.drop_constraint(None, 'contact_history', type_='foreignkey')
    op.create_foreign_key(op.f('fk_case'), 'contact_history', 'cases', ['case_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_contact_history_contact_time'), table_name='contact_history')
    op.drop_index(op.f('ix_contact_history_contact_id'), table_name='contact_history')
    op.create_index(op.f('idx_contact_history_created_by'), 'contact_history', ['created_by'], unique=False)
    op.create_index(op.f('idx_contact_history_contact_time'), 'contact_history', ['contact_time'], unique=False)
    op.create_index(op.f('idx_contact_history_case_id'), 'contact_history', ['case_id'], unique=False)
    op.create_unique_constraint(op.f('contact_history_contact_id_key'), 'contact_history', ['contact_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'compliance_violations', type_='foreignkey')
    op.drop_constraint(None, 'compliance_violations', type_='foreignkey')
    op.create_foreign_key(op.f('fk_contact_violation'), 'compliance_violations', 'contact_history', ['contact_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_case_violation'), 'compliance_violations', 'cases', ['case_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_compliance_violations_resolved'), table_name='compliance_violations')
    op.drop_index(op.f('ix_compliance_violations_detected_at'), table_name='compliance_violations')
    op.create_index(op.f('idx_compliance_violations_resolved'), 'compliance_violations', ['resolved'], unique=False)
    op.create_index(op.f('idx_compliance_violations_detected_at'), 'compliance_violations', ['detected_at'], unique=False)
    op.create_index(op.f('idx_compliance_violations_case_id'), 'compliance_violations', ['case_id'], unique=False)
    op.create_foreign_key(op.f('fk_assigned_to'), 'cases', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_cases_status'), table_name='cases')
    op.drop_index(op.f('ix_cases_overdue_days'), table_name='cases')
    op.drop_index(op.f('ix_cases_customer_id'), table_name='cases')
    op.drop_index(op.f('ix_cases_created_at'), table_name='cases')
    op.drop_index(op.f('ix_cases_case_id'), table_name='cases')
    op.create_index(op.f('idx_cases_status'), 'cases', ['status'], unique=False)
    op.create_index(op.f('idx_cases_overdue_days'), 'cases', ['overdue_days'], unique=False)
    op.create_index(op.f('idx_cases_customer_id'), 'cases', ['customer_id'], unique=False)
    op.create_index(op.f('idx_cases_created_at'), 'cases', ['created_at'], unique=False)
    op.create_index(op.f('idx_cases_assigned_to'), 'cases', ['assigned_to'], unique=False)
    op.create_unique_constraint(op.f('cases_case_id_key'), 'cases', ['case_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('cases', 'payment_promise',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('cases', 'overdue_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
    op.alter_column('cases', 'overdue_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    op.alter_column('cases', 'principal_amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=15, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
